name: Type Check

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Node and Check Types
      uses: actions/setup-node@v4
      with:
        node-version: 21
    - run: npm install
    - run: npm run build