name: Test

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Start SurrealDB
        uses: surrealdb/setup-surreal@v1
        with:
          surrealdb_version: latest
          surrealdb_port: 8000
          surrealdb_auth: false
          surrealdb_strict: false
          surrealdb_log: info
          surrealdb_additional_args: --allow-all
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm install
      - run: npm test
        env:
          SURREAL_DATABASE: itachi
          SURREAL_URL: http://surrealdb:8000/rpc