name: Test

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      surrealdb:
        image: dormammun/surreal-simple:latest
        ports:
          - 8000:8000
        options: >-
          --health-cmd "curl -f http://127.0.0.1:8000/health || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm install
      - run: npm test
        env:
          SURREAL_DATABASE: itachi
          SURREAL_URL: http://surrealdb:8000/rpc